name: Publish Release
on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate .patch
      run: perl Porting/make_dot_patch.pl
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        title: ${{ github.sha }}
        files: |
          README.md
          *.patch
